<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<style>
table, th, td {
    border: 1px solid black;
}
</style>
</head>
<body>

	<table><tbody>
                    <tr>
                    <td colspan="18">MEDIDA DE NIVELES DE ILUMINANCIA M&Eacute;TODO DE LOS NUEVE PUNTOS Y PROMEDIO HORIZONTAL</td>
                    </tr>
                    <tr>
                    <td colspan="2">RESPONSABLE</td> 
                    <td colspan="8"></td>
                    <td colspan="3">FECHA Y HORA</td>
                    <td colspan="5"></td>
                    </tr>
                    <tr>
                    <td colspan="8">CLASE DE ILUMINACION VEHICULAR</td>
                    <td colspan="10">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="">&nbsp;TRAMO</td>
                    <td colspan="7">&nbsp;</td>
                    <td colspan="2">&nbsp;DIRECCION L1</td>
                    <td colspan="4">&nbsp;</td>
                    <td colspan="2">&nbsp;DIRECCION L2</td>
                    <td colspan="4">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="">BARRIO</td>
                    <td colspan="10">&nbsp;</td>
                    <td colspan="">LUXMETRO</td>
                    <td colspan="8">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="8">CONDICIONES ATMOSFERICAS DE LA NOCHE</td>
                    <td colspan="10">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="">&nbsp;LUMINARIA L1</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="">&nbsp;BOMBILLA (POTENCIA)</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="">&nbsp;BOMBILLA (FUENTE)</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="">&nbsp;TIPO DE APOYO</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="">&nbsp;LONGITUD DE POSTE</td>
                    <td colspan="3">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="5">AVANCE LUMINARIA SOBRE LA CALZADA (m)</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="5">DISTANCIA DEL POSTE AL BORDE DE LA CALZADA(m)</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="5">ALTURA DEL MONTAJE DE LA LUMINARIA (m)</td>
                    <td colspan="">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="">&nbsp;ANGULO DE INCLINACION DE LA LUMINARIA</td>
                    <td colspan="5">&nbsp;</td>
                    <td colspan="">&nbsp;TENSION NOMINAL DE LA LUMINARIA</td>
                    <td colspan="5">&nbsp;</td>
                    <td colspan="">&nbsp;TENSION MEDIDA EN LA RED</td>
                    <td colspan="5">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="8">&nbsp;ESTADO DE LA LUMINARIA POR POLUCION</td>
                    <td colspan="10">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="">&nbsp;LUMINARIA L2</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="">&nbsp;BOMBILLA (POTENCIA)</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="">&nbsp;BOMBILLA (FUENTE)</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="">&nbsp;TIPO DE APOYO</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="">&nbsp;LONGITUD DE POSTE</td>
                    <td colspan="3">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="5">AVANCE LUMINARIA SOBRE LA CALZADA (m)</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="5">DISTANCIA DEL POSTE AL BORDE DE LA CALZADA(m)</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="5">ALTURA DEL MONTAJE DE LA LUMINARIA (m)</td>
                    <td colspan="">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="">&nbsp;ANGULO DE INCLINACION DE LA LUMINARIA</td>
                    <td colspan="5">&nbsp;</td>
                    <td colspan="">&nbsp;TENSION NOMINAL DE LA LUMINARIA</td>
                    <td colspan="5">&nbsp;</td>
                    <td colspan="">&nbsp;TENSION MEDIDA EN LA RED</td>
                    <td colspan="5">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="8">&nbsp;ESTADO DE LA LUMINARIA POR POLUCION</td>
                    <td colspan="10">&nbsp;</td>
                    </tr>
                    <tr>
                    <th colspan="9" rowspan="2">METODO NUEVE PUNTOS</th>
                    <th>1</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                    <th>6</th>
                    <th>7</th>
                    <th>8</th>
                    <th>9</th>
                    </tr>
                    <tr>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    </tr>
                    <tr>
                    <th colspan="8">ANDEN ADYACENTE</th>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    
                    </tr>
                    <tr>
                    <th colspan="8">ANDEN OPUESTO</th>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    <td colspan="">&nbsp;</td>
                    
                    </tr>
                    <tr>
                    <td colspan="18">&nbsp;</td>
                    </tr>
                    <tr>
                    <th colspan="3" rowspan="2">ILUMINANCIA</th>
                    <th colspan="4">VALOR PROMEDIO</th>
                    <th colspan="3">UNIFORMIDAD</th>
                    <th colspan="2">VALOR</th>
                    <th colspan="2">VALOR</th>
                    <th colspan="2">VALOR</th>
                    <th colspan="2">VALOR</th>
                    </tr>
                    <tr>
                    <th colspan="4">Eprom</th>
                    <td colspan="3">GENERAL (Uo)</td>
                    <td colspan="2">MINIMO</td>
                    <td colspan="2">MAXIMO</td>
                    <td colspan="2">MIN/MAX</td>
                    <td colspan="2">PROMEDIO/MAX</td>
                    </tr>
                    <tr>
                    <th colspan="3">CALZADA</th>
                    <td colspan="4">&nbsp;</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    </tr>
                    <tr>
                    <th colspan="3">ANDEN ADYACENTE</th>
                    <td colspan="4">&nbsp;</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    </tr>
                    <tr>
                    <th colspan="3">ANDEN OPUESTO</th>
                    <td colspan="4">&nbsp;</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    </tr>
                    <tr>
                    <td colspan="18">&nbsp;</td>
                    </tr>
                    <tr>
                    <th colspan="3">OBSERVACIONES</th>
                    <td colspan="15">&nbsp;</td>
                    </tr>
                     <tr>
                    <th colspan="3">CUMPLIMIENTO</th>
                    <td colspan="15">&nbsp;</td>
                    </tr> 
                       <tr>
                    <th colspan="3">POSIBLE SOLUCION</th>
                    <td colspan="15">&nbsp;</td>
                    </tr>
                    </tbody>
                    </table>
</body>
</html>
